services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sso-test
  auth-front:
    tty: true
    build:
      context: ./authFront
      dockerfile: Dockerfile
    volumes:
      - ./authFront/src:/app/src
    ports:
      - 8080:3000
    depends_on:
      - auth-back
  auth-back:
    tty: true
    build:
      context: ./authBack
      dockerfile: Dockerfile
    volumes:
      - ./authBack:/app
      - /app/node_modules
    ports:
      - 8081:3000
  sample1-front:
    tty: true
    build:
      context: ./sample1Front
      dockerfile: Dockerfile
    volumes:
      - ./sample1Front/src:/app/src
    ports:
      - 8000:3000
    depends_on:
      - sample1-back
  sample1-back:
    tty: true
    build:
      context: ./sample1Back
      dockerfile: Dockerfile
    volumes:
      - ./sample1Back:/app
      - /app/node_modules
    ports:
      - 8001:3000
    depends_on:
      - auth-front